//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_EPEC_CRT_ORDER_REQ_A_IN {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_EPEC_CRT_ORDER_REQ_A_OUTBinding", Namespace="urn:sinopec:ecc:wzerp:epec:integration")]
    public partial class SI_EPEC_CRT_ORDER_REQ_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_EPEC_CRT_ORDER_REQ_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_EPEC_CRT_ORDER_REQ_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_EPEC_CRT_ORDER_REQ_A_IN_SI_EPEC_CRT_ORDER_REQ_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_EPEC_CRT_ORDER_REQ_A_OUTCompletedEventHandler SI_EPEC_CRT_ORDER_REQ_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_EPEC_CRT_ORDER_REQ_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ecc:wzerp:epec:integration")] DT_EPEC_CRT_ORDER_REQ MT_EPEC_CRT_ORDER_REQ) {
            this.Invoke("SI_EPEC_CRT_ORDER_REQ_A_OUT", new object[] {
                        MT_EPEC_CRT_ORDER_REQ});
        }
        
        /// <remarks/>
        public void SI_EPEC_CRT_ORDER_REQ_A_OUTAsync(DT_EPEC_CRT_ORDER_REQ MT_EPEC_CRT_ORDER_REQ) {
            this.SI_EPEC_CRT_ORDER_REQ_A_OUTAsync(MT_EPEC_CRT_ORDER_REQ, null);
        }
        
        /// <remarks/>
        public void SI_EPEC_CRT_ORDER_REQ_A_OUTAsync(DT_EPEC_CRT_ORDER_REQ MT_EPEC_CRT_ORDER_REQ, object userState) {
            if ((this.SI_EPEC_CRT_ORDER_REQ_A_OUTOperationCompleted == null)) {
                this.SI_EPEC_CRT_ORDER_REQ_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_EPEC_CRT_ORDER_REQ_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_EPEC_CRT_ORDER_REQ_A_OUT", new object[] {
                        MT_EPEC_CRT_ORDER_REQ}, this.SI_EPEC_CRT_ORDER_REQ_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_EPEC_CRT_ORDER_REQ_A_OUTOperationCompleted(object arg) {
            if ((this.SI_EPEC_CRT_ORDER_REQ_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_EPEC_CRT_ORDER_REQ_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:ecc:wzerp:epec:integration")]
    public partial class DT_EPEC_CRT_ORDER_REQ {
        
        private DT_EPEC_CRT_ORDER_REQIS_MSG_HEAD iS_MSG_HEADField;
        
        private DT_EPEC_CRT_ORDER_REQIT_NXJH_HEAD[] iT_NXJH_HEADField;
        
        private DT_EPEC_CRT_ORDER_REQIT_DD_ITEM[] iT_DD_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EPEC_CRT_ORDER_REQIS_MSG_HEAD IS_MSG_HEAD {
            get {
                return this.iS_MSG_HEADField;
            }
            set {
                this.iS_MSG_HEADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_NXJH_HEAD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EPEC_CRT_ORDER_REQIT_NXJH_HEAD[] IT_NXJH_HEAD {
            get {
                return this.iT_NXJH_HEADField;
            }
            set {
                this.iT_NXJH_HEADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_DD_ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EPEC_CRT_ORDER_REQIT_DD_ITEM[] IT_DD_ITEM {
            get {
                return this.iT_DD_ITEMField;
            }
            set {
                this.iT_DD_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:wzerp:epec:integration")]
    public partial class DT_EPEC_CRT_ORDER_REQIS_MSG_HEAD {
        
        private string mANDTField;
        
        private string gUIDField;
        
        private string pROXY_IDField;
        
        private string sYSTEM_IDField;
        
        private string oPERATORField;
        
        private string sPRASField;
        
        private string iNTERFACE_IDField;
        
        private string sENDERField;
        
        private string rECIVERField;
        
        private string sENDTIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROXY_ID {
            get {
                return this.pROXY_IDField;
            }
            set {
                this.pROXY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SYSTEM_ID {
            get {
                return this.sYSTEM_IDField;
            }
            set {
                this.sYSTEM_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPERATOR {
            get {
                return this.oPERATORField;
            }
            set {
                this.oPERATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SPRAS {
            get {
                return this.sPRASField;
            }
            set {
                this.sPRASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERFACE_ID {
            get {
                return this.iNTERFACE_IDField;
            }
            set {
                this.iNTERFACE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SENDER {
            get {
                return this.sENDERField;
            }
            set {
                this.sENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RECIVER {
            get {
                return this.rECIVERField;
            }
            set {
                this.rECIVERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SENDTIME {
            get {
                return this.sENDTIMEField;
            }
            set {
                this.sENDTIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:wzerp:epec:integration")]
    public partial class DT_EPEC_CRT_ORDER_REQIT_NXJH_HEAD {
        
        private string zZXXHField;
        
        private string lOGSYSField;
        
        private string zZEPECLNField;
        
        private string zZEPECSNField;
        
        private string zZEPECIDField;
        
        private string zZEPECLNSOField;
        
        private string zZEPECSNSOField;
        
        private string sTRSUBTIMEField;
        
        private string sTRCONTIMEField;
        
        private string zZYFField;
        
        private string zKUUNRField;
        
        private string lIFNRField;
        
        private string sTRMEMLOGNAMEField;
        
        private string iSPOField;
        
        private string uSEFLAGField;
        
        private string iNTSTATUS2Field;
        
        private string dAOPTField;
        
        private string uRNAMField;
        
        private string eRDATField;
        
        private string zZHTLBField;
        
        private string zZMANAMODEField;
        
        private string zZINTATTRTYPEField;
        
        private string zZZFFSBMField;
        
        private string zZKHSXField;
        
        private string zZYL1Field;
        
        private string zZYL2Field;
        
        private string zZYL3Field;
        
        private string zZYL4Field;
        
        private string zZYL5Field;
        
        private string zZYL6Field;
        
        private string zZYL7Field;
        
        private string zZYL8Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZXXH {
            get {
                return this.zZXXHField;
            }
            set {
                this.zZXXHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGSYS {
            get {
                return this.lOGSYSField;
            }
            set {
                this.lOGSYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZEPECLN {
            get {
                return this.zZEPECLNField;
            }
            set {
                this.zZEPECLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZEPECSN {
            get {
                return this.zZEPECSNField;
            }
            set {
                this.zZEPECSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZEPECID {
            get {
                return this.zZEPECIDField;
            }
            set {
                this.zZEPECIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZEPECLNSO {
            get {
                return this.zZEPECLNSOField;
            }
            set {
                this.zZEPECLNSOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZEPECSNSO {
            get {
                return this.zZEPECSNSOField;
            }
            set {
                this.zZEPECSNSOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRSUBTIME {
            get {
                return this.sTRSUBTIMEField;
            }
            set {
                this.sTRSUBTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRCONTIME {
            get {
                return this.sTRCONTIMEField;
            }
            set {
                this.sTRCONTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYF {
            get {
                return this.zZYFField;
            }
            set {
                this.zZYFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZKUUNR {
            get {
                return this.zKUUNRField;
            }
            set {
                this.zKUUNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRMEMLOGNAME {
            get {
                return this.sTRMEMLOGNAMEField;
            }
            set {
                this.sTRMEMLOGNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISPO {
            get {
                return this.iSPOField;
            }
            set {
                this.iSPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USEFLAG {
            get {
                return this.uSEFLAGField;
            }
            set {
                this.uSEFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTSTATUS2 {
            get {
                return this.iNTSTATUS2Field;
            }
            set {
                this.iNTSTATUS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DAOPT {
            get {
                return this.dAOPTField;
            }
            set {
                this.dAOPTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URNAM {
            get {
                return this.uRNAMField;
            }
            set {
                this.uRNAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERDAT {
            get {
                return this.eRDATField;
            }
            set {
                this.eRDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZHTLB {
            get {
                return this.zZHTLBField;
            }
            set {
                this.zZHTLBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZMANAMODE {
            get {
                return this.zZMANAMODEField;
            }
            set {
                this.zZMANAMODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZINTATTRTYPE {
            get {
                return this.zZINTATTRTYPEField;
            }
            set {
                this.zZINTATTRTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZZFFSBM {
            get {
                return this.zZZFFSBMField;
            }
            set {
                this.zZZFFSBMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZKHSX {
            get {
                return this.zZKHSXField;
            }
            set {
                this.zZKHSXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL1 {
            get {
                return this.zZYL1Field;
            }
            set {
                this.zZYL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL2 {
            get {
                return this.zZYL2Field;
            }
            set {
                this.zZYL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL3 {
            get {
                return this.zZYL3Field;
            }
            set {
                this.zZYL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL4 {
            get {
                return this.zZYL4Field;
            }
            set {
                this.zZYL4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL5 {
            get {
                return this.zZYL5Field;
            }
            set {
                this.zZYL5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL6 {
            get {
                return this.zZYL6Field;
            }
            set {
                this.zZYL6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL7 {
            get {
                return this.zZYL7Field;
            }
            set {
                this.zZYL7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL8 {
            get {
                return this.zZYL8Field;
            }
            set {
                this.zZYL8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:wzerp:epec:integration")]
    public partial class DT_EPEC_CRT_ORDER_REQIT_DD_ITEM {
        
        private string zZEPECSNField;
        
        private string eBELPField;
        
        private string mATNRField;
        
        private string nETPRField;
        
        private string wAERSField;
        
        private string mENGEField;
        
        private string mEINSField;
        
        private string mWSKZField;
        
        private string kONNRField;
        
        private string eINDTField;
        
        private string vBELNField;
        
        private string vBELPField;
        
        private string zZYL1Field;
        
        private string zZYL2Field;
        
        private string zZYL3Field;
        
        private string zZYL4Field;
        
        private string zZYL5Field;
        
        private string zZYL6Field;
        
        private string zZYL7Field;
        
        private string zZYL8Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZEPECSN {
            get {
                return this.zZEPECSNField;
            }
            set {
                this.zZEPECSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NETPR {
            get {
                return this.nETPRField;
            }
            set {
                this.nETPRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MWSKZ {
            get {
                return this.mWSKZField;
            }
            set {
                this.mWSKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KONNR {
            get {
                return this.kONNRField;
            }
            set {
                this.kONNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELP {
            get {
                return this.vBELPField;
            }
            set {
                this.vBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL1 {
            get {
                return this.zZYL1Field;
            }
            set {
                this.zZYL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL2 {
            get {
                return this.zZYL2Field;
            }
            set {
                this.zZYL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL3 {
            get {
                return this.zZYL3Field;
            }
            set {
                this.zZYL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL4 {
            get {
                return this.zZYL4Field;
            }
            set {
                this.zZYL4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL5 {
            get {
                return this.zZYL5Field;
            }
            set {
                this.zZYL5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL6 {
            get {
                return this.zZYL6Field;
            }
            set {
                this.zZYL6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL7 {
            get {
                return this.zZYL7Field;
            }
            set {
                this.zZYL7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZYL8 {
            get {
                return this.zZYL8Field;
            }
            set {
                this.zZYL8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_EPEC_CRT_ORDER_REQ_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591