//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_EC5_ERP_LOGISTICS_CONTRACT1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_EC5_LOGISTICS_CONTRACT_A_OUTBinding", Namespace="urn:sinopec:ec5:wzerp:contract")]
    public partial class SI_EC5_LOGISTICS_CONTRACT_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_EC5_LOGISTICS_CONTRACT_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_EC5_LOGISTICS_CONTRACT_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_EC5_ERP_LOGISTICS_CONTRACT1_SI_EC5_LOGISTICS_CONTRACT_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_EC5_LOGISTICS_CONTRACT_A_OUTCompletedEventHandler SI_EC5_LOGISTICS_CONTRACT_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_EC5_LOGISTICS_CONTRACT_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ec5:wzerp:contract")] CONTRACTWL CONTRACTWL) {
            this.Invoke("SI_EC5_LOGISTICS_CONTRACT_A_OUT", new object[] {
                        CONTRACTWL});
        }
        
        /// <remarks/>
        public void SI_EC5_LOGISTICS_CONTRACT_A_OUTAsync(CONTRACTWL CONTRACTWL) {
            this.SI_EC5_LOGISTICS_CONTRACT_A_OUTAsync(CONTRACTWL, null);
        }
        
        /// <remarks/>
        public void SI_EC5_LOGISTICS_CONTRACT_A_OUTAsync(CONTRACTWL CONTRACTWL, object userState) {
            if ((this.SI_EC5_LOGISTICS_CONTRACT_A_OUTOperationCompleted == null)) {
                this.SI_EC5_LOGISTICS_CONTRACT_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_EC5_LOGISTICS_CONTRACT_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_EC5_LOGISTICS_CONTRACT_A_OUT", new object[] {
                        CONTRACTWL}, this.SI_EC5_LOGISTICS_CONTRACT_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_EC5_LOGISTICS_CONTRACT_A_OUTOperationCompleted(object arg) {
            if ((this.SI_EC5_LOGISTICS_CONTRACT_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_EC5_LOGISTICS_CONTRACT_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:wzerp:contract")]
    public partial class CONTRACTWL {
        
        private string mSGIDField;
        
        private string sTRSYSNUMBERField;
        
        private string pONOField;
        
        private string eCPONOField;
        
        private string sUPPCODEField;
        
        private string vENDORCODEField;
        
        private string cORPCODEField;
        
        private string cORPCODEN4Field;
        
        private string eRPGROUPField;
        
        private string cREATEUSERField;
        
        private string dASUBTIMEField;
        
        private string kONNRField;
        
        private string sTOCKTYPEField;
        
        private string tOTALSAVEAMOUNTField;
        
        private string cREATEDATEField;
        
        private string oUTPORTField;
        
        private string aRRIVEPORTField;
        
        private string dOWNLOADDATEField;
        
        private string iFLAGField;
        
        private CONTRACTWLCONTRACTWLMAT[] cONTRACTWLMATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRSYSNUMBER {
            get {
                return this.sTRSYSNUMBERField;
            }
            set {
                this.sTRSYSNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PONO {
            get {
                return this.pONOField;
            }
            set {
                this.pONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ECPONO {
            get {
                return this.eCPONOField;
            }
            set {
                this.eCPONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUPPCODE {
            get {
                return this.sUPPCODEField;
            }
            set {
                this.sUPPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDORCODE {
            get {
                return this.vENDORCODEField;
            }
            set {
                this.vENDORCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPCODE {
            get {
                return this.cORPCODEField;
            }
            set {
                this.cORPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPCODEN4 {
            get {
                return this.cORPCODEN4Field;
            }
            set {
                this.cORPCODEN4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPGROUP {
            get {
                return this.eRPGROUPField;
            }
            set {
                this.eRPGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATEUSER {
            get {
                return this.cREATEUSERField;
            }
            set {
                this.cREATEUSERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DASUBTIME {
            get {
                return this.dASUBTIMEField;
            }
            set {
                this.dASUBTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KONNR {
            get {
                return this.kONNRField;
            }
            set {
                this.kONNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCKTYPE {
            get {
                return this.sTOCKTYPEField;
            }
            set {
                this.sTOCKTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALSAVEAMOUNT {
            get {
                return this.tOTALSAVEAMOUNTField;
            }
            set {
                this.tOTALSAVEAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATEDATE {
            get {
                return this.cREATEDATEField;
            }
            set {
                this.cREATEDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OUTPORT {
            get {
                return this.oUTPORTField;
            }
            set {
                this.oUTPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ARRIVEPORT {
            get {
                return this.aRRIVEPORTField;
            }
            set {
                this.aRRIVEPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOWNLOADDATE {
            get {
                return this.dOWNLOADDATEField;
            }
            set {
                this.dOWNLOADDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFLAG {
            get {
                return this.iFLAGField;
            }
            set {
                this.iFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTRACTWLMAT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CONTRACTWLCONTRACTWLMAT[] CONTRACTWLMAT {
            get {
                return this.cONTRACTWLMATField;
            }
            set {
                this.cONTRACTWLMATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:wzerp:contract")]
    public partial class CONTRACTWLCONTRACTWLMAT {
        
        private string pRNOField;
        
        private string eCORDERCODEField;
        
        private string pRODCODEField;
        
        private string yFBZField;
        
        private string yFHLField;
        
        private string dASTARTDATEField;
        
        private string dAENDDATEField;
        
        private string gWZXFField;
        
        private string gWGKFYField;
        
        private string gWBGBJField;
        
        private string gWLYFField;
        
        private string gWHYFField;
        
        private string gWKYFField;
        
        private string gWQTFYField;
        
        private string gWFYBZField;
        
        private string gNBGBJField;
        
        private string gNGKFYField;
        
        private string gNCXFField;
        
        private string gNLYFField;
        
        private string gNSYFField;
        
        private string gNKYFField;
        
        private string gNQTFYField;
        
        private string gNFYBZField;
        
        private string iNTTAXField;
        
        private string iNTAVGPRICEField;
        
        private string eNQUTYPEField;
        
        private string tECHSTANDARDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRNO {
            get {
                return this.pRNOField;
            }
            set {
                this.pRNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ECORDERCODE {
            get {
                return this.eCORDERCODEField;
            }
            set {
                this.eCORDERCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODCODE {
            get {
                return this.pRODCODEField;
            }
            set {
                this.pRODCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YFBZ {
            get {
                return this.yFBZField;
            }
            set {
                this.yFBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YFHL {
            get {
                return this.yFHLField;
            }
            set {
                this.yFHLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DASTARTDATE {
            get {
                return this.dASTARTDATEField;
            }
            set {
                this.dASTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DAENDDATE {
            get {
                return this.dAENDDATEField;
            }
            set {
                this.dAENDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWZXF {
            get {
                return this.gWZXFField;
            }
            set {
                this.gWZXFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWGKFY {
            get {
                return this.gWGKFYField;
            }
            set {
                this.gWGKFYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWBGBJ {
            get {
                return this.gWBGBJField;
            }
            set {
                this.gWBGBJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWLYF {
            get {
                return this.gWLYFField;
            }
            set {
                this.gWLYFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWHYF {
            get {
                return this.gWHYFField;
            }
            set {
                this.gWHYFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWKYF {
            get {
                return this.gWKYFField;
            }
            set {
                this.gWKYFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWQTFY {
            get {
                return this.gWQTFYField;
            }
            set {
                this.gWQTFYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GWFYBZ {
            get {
                return this.gWFYBZField;
            }
            set {
                this.gWFYBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNBGBJ {
            get {
                return this.gNBGBJField;
            }
            set {
                this.gNBGBJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNGKFY {
            get {
                return this.gNGKFYField;
            }
            set {
                this.gNGKFYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNCXF {
            get {
                return this.gNCXFField;
            }
            set {
                this.gNCXFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNLYF {
            get {
                return this.gNLYFField;
            }
            set {
                this.gNLYFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNSYF {
            get {
                return this.gNSYFField;
            }
            set {
                this.gNSYFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNKYF {
            get {
                return this.gNKYFField;
            }
            set {
                this.gNKYFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNQTFY {
            get {
                return this.gNQTFYField;
            }
            set {
                this.gNQTFYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GNFYBZ {
            get {
                return this.gNFYBZField;
            }
            set {
                this.gNFYBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTTAX {
            get {
                return this.iNTTAXField;
            }
            set {
                this.iNTTAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTAVGPRICE {
            get {
                return this.iNTAVGPRICEField;
            }
            set {
                this.iNTAVGPRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENQUTYPE {
            get {
                return this.eNQUTYPEField;
            }
            set {
                this.eNQUTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TECHSTANDARD {
            get {
                return this.tECHSTANDARDField;
            }
            set {
                this.tECHSTANDARDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_EC5_LOGISTICS_CONTRACT_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591