//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_EC5_STOCK_AUTHORIZE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTBinding", Namespace="urn:sinopec:ec5:wzerp:purchase:control:integration")]
    public partial class SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_EC5_STOCK_AUTHORIZE_SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTCompletedEventHandler SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_EC5_STOCK_AUTHORIZE_REQ_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:wzerp:ec5:purchase:control:integration")] DT_EC5_WZERP_STOCK_AUTHORIZE_REQ STOCKAUTHORIZE) {
            this.Invoke("SI_EC5_STOCK_AUTHORIZE_REQ_A_OUT", new object[] {
                        STOCKAUTHORIZE});
        }
        
        /// <remarks/>
        public void SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTAsync(DT_EC5_WZERP_STOCK_AUTHORIZE_REQ STOCKAUTHORIZE) {
            this.SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTAsync(STOCKAUTHORIZE, null);
        }
        
        /// <remarks/>
        public void SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTAsync(DT_EC5_WZERP_STOCK_AUTHORIZE_REQ STOCKAUTHORIZE, object userState) {
            if ((this.SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTOperationCompleted == null)) {
                this.SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_EC5_STOCK_AUTHORIZE_REQ_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_EC5_STOCK_AUTHORIZE_REQ_A_OUT", new object[] {
                        STOCKAUTHORIZE}, this.SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_EC5_STOCK_AUTHORIZE_REQ_A_OUTOperationCompleted(object arg) {
            if ((this.SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:wzerp:ec5:purchase:control:integration")]
    public partial class DT_EC5_WZERP_STOCK_AUTHORIZE_REQ {
        
        private string mSGIDField;
        
        private string sTRSYSNUMBERField;
        
        private string bUSINESSTYPEField;
        
        private DT_EC5_WZERP_STOCK_AUTHORIZE_REQSTOCKAUTHORIZELIST[] sTOCKAUTHORIZELISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRSYSNUMBER {
            get {
                return this.sTRSYSNUMBERField;
            }
            set {
                this.sTRSYSNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUSINESSTYPE {
            get {
                return this.bUSINESSTYPEField;
            }
            set {
                this.bUSINESSTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("STOCKAUTHORIZELIST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EC5_WZERP_STOCK_AUTHORIZE_REQSTOCKAUTHORIZELIST[] STOCKAUTHORIZELIST {
            get {
                return this.sTOCKAUTHORIZELISTField;
            }
            set {
                this.sTOCKAUTHORIZELISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:wzerp:ec5:purchase:control:integration")]
    public partial class DT_EC5_WZERP_STOCK_AUTHORIZE_REQSTOCKAUTHORIZELIST {
        
        private string sTRORDERCODEField;
        
        private string pZWT_NOField;
        
        private string iNTTYPEField;
        
        private string iNTCODE_TRANField;
        
        private string iNTCODE_TOField;
        
        private string sTRMEMNAMEField;
        
        private string dASUBTIMEField;
        
        private string iNTATTRTYPEField;
        
        private string iNTFLAGField;
        
        private string sTRPLANNOField;
        
        private string sTRURLField;
        
        private string dALEADTIMEField;
        
        private string iNTCOCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRORDERCODE {
            get {
                return this.sTRORDERCODEField;
            }
            set {
                this.sTRORDERCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PZWT_NO {
            get {
                return this.pZWT_NOField;
            }
            set {
                this.pZWT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTTYPE {
            get {
                return this.iNTTYPEField;
            }
            set {
                this.iNTTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTCODE_TRAN {
            get {
                return this.iNTCODE_TRANField;
            }
            set {
                this.iNTCODE_TRANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTCODE_TO {
            get {
                return this.iNTCODE_TOField;
            }
            set {
                this.iNTCODE_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRMEMNAME {
            get {
                return this.sTRMEMNAMEField;
            }
            set {
                this.sTRMEMNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DASUBTIME {
            get {
                return this.dASUBTIMEField;
            }
            set {
                this.dASUBTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTATTRTYPE {
            get {
                return this.iNTATTRTYPEField;
            }
            set {
                this.iNTATTRTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTFLAG {
            get {
                return this.iNTFLAGField;
            }
            set {
                this.iNTFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRPLANNO {
            get {
                return this.sTRPLANNOField;
            }
            set {
                this.sTRPLANNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRURL {
            get {
                return this.sTRURLField;
            }
            set {
                this.sTRURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DALEADTIME {
            get {
                return this.dALEADTIMEField;
            }
            set {
                this.dALEADTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTCOCODE {
            get {
                return this.iNTCOCODEField;
            }
            set {
                this.iNTCOCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591