//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_IDEC_PO2ECC_REQ_A {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_IDEC_PO2ECC_REQ_A_OUTBinding", Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class SI_IDEC_PO2ECC_REQ_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_IDEC_PO2ECC_REQ_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public SI_IDEC_PO2ECC_REQ_A_OUTService()
        {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_IDEC_PO2ECC_REQ_A_SI_IDEC_PO2ECC_REQ_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_IDEC_PO2ECC_REQ_A_OUTCompletedEventHandler SI_IDEC_PO2ECC_REQ_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_IDEC_PO2ECC_REQ_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ecc:mm:idec_mro")] DT_IDEC_PO2ECC_REQ MT_IDEC_PO2ECC_REQ) {
            this.Invoke("SI_IDEC_PO2ECC_REQ_A_OUT", new object[] {
                        MT_IDEC_PO2ECC_REQ});
        }
        
        /// <remarks/>
        public void SI_IDEC_PO2ECC_REQ_A_OUTAsync(DT_IDEC_PO2ECC_REQ MT_IDEC_PO2ECC_REQ) {
            this.SI_IDEC_PO2ECC_REQ_A_OUTAsync(MT_IDEC_PO2ECC_REQ, null);
        }
        
        /// <remarks/>
        public void SI_IDEC_PO2ECC_REQ_A_OUTAsync(DT_IDEC_PO2ECC_REQ MT_IDEC_PO2ECC_REQ, object userState) {
            if ((this.SI_IDEC_PO2ECC_REQ_A_OUTOperationCompleted == null)) {
                this.SI_IDEC_PO2ECC_REQ_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_IDEC_PO2ECC_REQ_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_IDEC_PO2ECC_REQ_A_OUT", new object[] {
                        MT_IDEC_PO2ECC_REQ}, this.SI_IDEC_PO2ECC_REQ_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_IDEC_PO2ECC_REQ_A_OUTOperationCompleted(object arg) {
            if ((this.SI_IDEC_PO2ECC_REQ_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_IDEC_PO2ECC_REQ_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class DT_IDEC_PO2ECC_REQ {
        
        private DT_IDEC_PO2ECC_REQIT_ZMROSZYSCPOH[] iT_ZMROSZYSCPOHField;
        
        private DT_IDEC_PO2ECC_REQIT_ZMROSZYSCPOL[] iT_ZMROSZYSCPOLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_ZMROSZYSCPOH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_IDEC_PO2ECC_REQIT_ZMROSZYSCPOH[] IT_ZMROSZYSCPOH {
            get {
                return this.iT_ZMROSZYSCPOHField;
            }
            set {
                this.iT_ZMROSZYSCPOHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_ZMROSZYSCPOL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_IDEC_PO2ECC_REQIT_ZMROSZYSCPOL[] IT_ZMROSZYSCPOL {
            get {
                return this.iT_ZMROSZYSCPOLField;
            }
            set {
                this.iT_ZMROSZYSCPOLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class DT_IDEC_PO2ECC_REQIT_ZMROSZYSCPOH {
        
        private string mSGIDField;
        
        private string lOGSYSField;
        
        private string vENDOR_NOField;
        
        private string wERKSField;
        
        private string pUR_ORGField;
        
        private string pUR_GRPField;
        
        private string pUR_DATEField;
        
        private string zIDECDDHField;
        
        private string zIDECKEYField;
        
        private string uNAMEField;
        
        private string dOC_TYPEField;
        
        private string bUKRSField;
        
        private string rESERVE1Field;
        
        private string rESERVE2Field;
        
        private string rESERVE3Field;
        
        private string rESERVE4Field;
        
        private string rESERVE5Field;
        
        private string rESERVE6Field;
        
        private string rESERVE7Field;
        
        private string rESERVE8Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGSYS {
            get {
                return this.lOGSYSField;
            }
            set {
                this.lOGSYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDOR_NO {
            get {
                return this.vENDOR_NOField;
            }
            set {
                this.vENDOR_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PUR_ORG {
            get {
                return this.pUR_ORGField;
            }
            set {
                this.pUR_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PUR_GRP {
            get {
                return this.pUR_GRPField;
            }
            set {
                this.pUR_GRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PUR_DATE {
            get {
                return this.pUR_DATEField;
            }
            set {
                this.pUR_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECDDH {
            get {
                return this.zIDECDDHField;
            }
            set {
                this.zIDECDDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECKEY {
            get {
                return this.zIDECKEYField;
            }
            set {
                this.zIDECKEYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNAME {
            get {
                return this.uNAMEField;
            }
            set {
                this.uNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_TYPE {
            get {
                return this.dOC_TYPEField;
            }
            set {
                this.dOC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE1 {
            get {
                return this.rESERVE1Field;
            }
            set {
                this.rESERVE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE2 {
            get {
                return this.rESERVE2Field;
            }
            set {
                this.rESERVE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE3 {
            get {
                return this.rESERVE3Field;
            }
            set {
                this.rESERVE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE4 {
            get {
                return this.rESERVE4Field;
            }
            set {
                this.rESERVE4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE5 {
            get {
                return this.rESERVE5Field;
            }
            set {
                this.rESERVE5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE6 {
            get {
                return this.rESERVE6Field;
            }
            set {
                this.rESERVE6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE7 {
            get {
                return this.rESERVE7Field;
            }
            set {
                this.rESERVE7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE8 {
            get {
                return this.rESERVE8Field;
            }
            set {
                this.rESERVE8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class DT_IDEC_PO2ECC_REQIT_ZMROSZYSCPOL {
        
        private string zIDECKJXYField;
        
        private string zIDECDDHField;
        
        private string zIDECDDHXMHField;
        
        private string mAT_CODEField;
        
        private string pR_NOField;
        
        private string kNTTPField;
        
        private string kOSTLField;
        
        private string hKONTField;
        
        private string bWARTField;
        
        private string pSPIDField;
        
        private string zPOSIDPRField;
        
        private string zPOSIDPRTXTField;
        
        private string qUANTITYField;
        
        private string pRICEField;
        
        private string tRANSPORT_FEEField;
        
        private string iNTFREEField;
        
        private string kBETRField;
        
        private string oTHER_FEEField;
        
        private string tAX_CODEField;
        
        private string uNITField;
        
        private string dELIV_DATEField;
        
        private string sTOCK_NAMEField;
        
        private string sTRORDERCODEField;
        
        private string zCGBZField;
        
        private string zBDBZField;
        
        private string zECFWRATEField;
        
        private string zYL1Field;
        
        private string zYL2Field;
        
        private string zYL3Field;
        
        private string zYL4Field;
        
        private string zYL5Field;
        
        private string zYL6Field;
        
        private string zYL7Field;
        
        private string zYL8Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECKJXY {
            get {
                return this.zIDECKJXYField;
            }
            set {
                this.zIDECKJXYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECDDH {
            get {
                return this.zIDECDDHField;
            }
            set {
                this.zIDECDDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECDDHXMH {
            get {
                return this.zIDECDDHXMHField;
            }
            set {
                this.zIDECDDHXMHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAT_CODE {
            get {
                return this.mAT_CODEField;
            }
            set {
                this.mAT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PR_NO {
            get {
                return this.pR_NOField;
            }
            set {
                this.pR_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KNTTP {
            get {
                return this.kNTTPField;
            }
            set {
                this.kNTTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HKONT {
            get {
                return this.hKONTField;
            }
            set {
                this.hKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BWART {
            get {
                return this.bWARTField;
            }
            set {
                this.bWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSPID {
            get {
                return this.pSPIDField;
            }
            set {
                this.pSPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZPOSIDPR {
            get {
                return this.zPOSIDPRField;
            }
            set {
                this.zPOSIDPRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZPOSIDPRTXT {
            get {
                return this.zPOSIDPRTXTField;
            }
            set {
                this.zPOSIDPRTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRICE {
            get {
                return this.pRICEField;
            }
            set {
                this.pRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSPORT_FEE {
            get {
                return this.tRANSPORT_FEEField;
            }
            set {
                this.tRANSPORT_FEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTFREE {
            get {
                return this.iNTFREEField;
            }
            set {
                this.iNTFREEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KBETR {
            get {
                return this.kBETRField;
            }
            set {
                this.kBETRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OTHER_FEE {
            get {
                return this.oTHER_FEEField;
            }
            set {
                this.oTHER_FEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAX_CODE {
            get {
                return this.tAX_CODEField;
            }
            set {
                this.tAX_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DELIV_DATE {
            get {
                return this.dELIV_DATEField;
            }
            set {
                this.dELIV_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCK_NAME {
            get {
                return this.sTOCK_NAMEField;
            }
            set {
                this.sTOCK_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRORDERCODE {
            get {
                return this.sTRORDERCODEField;
            }
            set {
                this.sTRORDERCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCGBZ {
            get {
                return this.zCGBZField;
            }
            set {
                this.zCGBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBDBZ {
            get {
                return this.zBDBZField;
            }
            set {
                this.zBDBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZECFWRATE {
            get {
                return this.zECFWRATEField;
            }
            set {
                this.zECFWRATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL1 {
            get {
                return this.zYL1Field;
            }
            set {
                this.zYL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL2 {
            get {
                return this.zYL2Field;
            }
            set {
                this.zYL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL3 {
            get {
                return this.zYL3Field;
            }
            set {
                this.zYL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL4 {
            get {
                return this.zYL4Field;
            }
            set {
                this.zYL4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL5 {
            get {
                return this.zYL5Field;
            }
            set {
                this.zYL5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL6 {
            get {
                return this.zYL6Field;
            }
            set {
                this.zYL6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL7 {
            get {
                return this.zYL7Field;
            }
            set {
                this.zYL7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL8 {
            get {
                return this.zYL8Field;
            }
            set {
                this.zYL8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_IDEC_PO2ECC_REQ_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591