//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_WZERP_ZQ_IF001 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_WZERP_ZQ_IF001_A_OUTBinding", Namespace="urn:sinopec:ec5:zq:agreement")]
    public partial class SI_WZERP_ZQ_IF001_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_WZERP_ZQ_IF001_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_WZERP_ZQ_IF001_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_WZERP_ZQ_IF001_SI_WZERP_ZQ_IF001_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_WZERP_ZQ_IF001_A_OUTCompletedEventHandler SI_WZERP_ZQ_IF001_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_WZERP_ZQ_IF001_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ec5:zq:agreement")] DT_EC5_ZQ_IF001_REQ MT_EC5_ZQ_IF001_REQ) {
            this.Invoke("SI_WZERP_ZQ_IF001_A_OUT", new object[] {
                        MT_EC5_ZQ_IF001_REQ});
        }
        
        /// <remarks/>
        public void SI_WZERP_ZQ_IF001_A_OUTAsync(DT_EC5_ZQ_IF001_REQ MT_EC5_ZQ_IF001_REQ) {
            this.SI_WZERP_ZQ_IF001_A_OUTAsync(MT_EC5_ZQ_IF001_REQ, null);
        }
        
        /// <remarks/>
        public void SI_WZERP_ZQ_IF001_A_OUTAsync(DT_EC5_ZQ_IF001_REQ MT_EC5_ZQ_IF001_REQ, object userState) {
            if ((this.SI_WZERP_ZQ_IF001_A_OUTOperationCompleted == null)) {
                this.SI_WZERP_ZQ_IF001_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_WZERP_ZQ_IF001_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_WZERP_ZQ_IF001_A_OUT", new object[] {
                        MT_EC5_ZQ_IF001_REQ}, this.SI_WZERP_ZQ_IF001_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_WZERP_ZQ_IF001_A_OUTOperationCompleted(object arg) {
            if ((this.SI_WZERP_ZQ_IF001_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_WZERP_ZQ_IF001_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:ec5:zq:agreement")]
    public partial class DT_EC5_ZQ_IF001_REQ {
        
        private DT_EC5_ZQ_IF001_REQAGREEMENTWZERP aGREEMENTWZERPField;
        
        private DT_EC5_ZQ_IF001_REQAGREEMENTWZERPFILE[] aGREEMENTWZERPFILEField;
        
        private DT_EC5_ZQ_IF001_REQAGREEMENTWZERPPRODUCTS[] aGREEMENTWZERPPRODUCTSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EC5_ZQ_IF001_REQAGREEMENTWZERP AGREEMENTWZERP {
            get {
                return this.aGREEMENTWZERPField;
            }
            set {
                this.aGREEMENTWZERPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AGREEMENTWZERPFILE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EC5_ZQ_IF001_REQAGREEMENTWZERPFILE[] AGREEMENTWZERPFILE {
            get {
                return this.aGREEMENTWZERPFILEField;
            }
            set {
                this.aGREEMENTWZERPFILEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AGREEMENTWZERPPRODUCTS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EC5_ZQ_IF001_REQAGREEMENTWZERPPRODUCTS[] AGREEMENTWZERPPRODUCTS {
            get {
                return this.aGREEMENTWZERPPRODUCTSField;
            }
            set {
                this.aGREEMENTWZERPPRODUCTSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:zq:agreement")]
    public partial class DT_EC5_ZQ_IF001_REQAGREEMENTWZERP {
        
        private string mSGIDField;
        
        private string sTRNField;
        
        private string sENDTIMEField;
        
        private string sIGNSUPPField;
        
        private string aGREETYPEField;
        
        private string sIGNDATEField;
        
        private string cREATECORPField;
        
        private string sTARTDATEField;
        
        private string eNDDATEField;
        
        private string tARGETVALUEField;
        
        private string sTOCKTYPEField;
        
        private string aTTRTYPEField;
        
        private string aGRCODEField;
        
        private string oPERATETYPEField;
        
        private string sAPAGRCODEField;
        
        private string oPERATEDEPTField;
        
        private string cREATEUSERNAMEField;
        
        private string cREATECOMPNAMEField;
        
        private string uSERTELEPHONEField;
        
        private string bIDFILECODEField;
        
        private string bIDPACKNOField;
        
        private string bIDPROJECTNAMEField;
        
        private string aGREEMENTNAMEField;
        
        private string bIDNOTIFYTIMEField;
        
        private string yL1Field;
        
        private string yL2Field;
        
        private string yL3Field;
        
        private string yL4Field;
        
        private string yL5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRN {
            get {
                return this.sTRNField;
            }
            set {
                this.sTRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SENDTIME {
            get {
                return this.sENDTIMEField;
            }
            set {
                this.sENDTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGNSUPP {
            get {
                return this.sIGNSUPPField;
            }
            set {
                this.sIGNSUPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGREETYPE {
            get {
                return this.aGREETYPEField;
            }
            set {
                this.aGREETYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGNDATE {
            get {
                return this.sIGNDATEField;
            }
            set {
                this.sIGNDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATECORP {
            get {
                return this.cREATECORPField;
            }
            set {
                this.cREATECORPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARGETVALUE {
            get {
                return this.tARGETVALUEField;
            }
            set {
                this.tARGETVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCKTYPE {
            get {
                return this.sTOCKTYPEField;
            }
            set {
                this.sTOCKTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTRTYPE {
            get {
                return this.aTTRTYPEField;
            }
            set {
                this.aTTRTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRCODE {
            get {
                return this.aGRCODEField;
            }
            set {
                this.aGRCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPERATETYPE {
            get {
                return this.oPERATETYPEField;
            }
            set {
                this.oPERATETYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAPAGRCODE {
            get {
                return this.sAPAGRCODEField;
            }
            set {
                this.sAPAGRCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPERATEDEPT {
            get {
                return this.oPERATEDEPTField;
            }
            set {
                this.oPERATEDEPTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATEUSERNAME {
            get {
                return this.cREATEUSERNAMEField;
            }
            set {
                this.cREATEUSERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATECOMPNAME {
            get {
                return this.cREATECOMPNAMEField;
            }
            set {
                this.cREATECOMPNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERTELEPHONE {
            get {
                return this.uSERTELEPHONEField;
            }
            set {
                this.uSERTELEPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDFILECODE {
            get {
                return this.bIDFILECODEField;
            }
            set {
                this.bIDFILECODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDPACKNO {
            get {
                return this.bIDPACKNOField;
            }
            set {
                this.bIDPACKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDPROJECTNAME {
            get {
                return this.bIDPROJECTNAMEField;
            }
            set {
                this.bIDPROJECTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGREEMENTNAME {
            get {
                return this.aGREEMENTNAMEField;
            }
            set {
                this.aGREEMENTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDNOTIFYTIME {
            get {
                return this.bIDNOTIFYTIMEField;
            }
            set {
                this.bIDNOTIFYTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL1 {
            get {
                return this.yL1Field;
            }
            set {
                this.yL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL2 {
            get {
                return this.yL2Field;
            }
            set {
                this.yL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL3 {
            get {
                return this.yL3Field;
            }
            set {
                this.yL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL4 {
            get {
                return this.yL4Field;
            }
            set {
                this.yL4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL5 {
            get {
                return this.yL5Field;
            }
            set {
                this.yL5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:zq:agreement")]
    public partial class DT_EC5_ZQ_IF001_REQAGREEMENTWZERPFILE {
        
        private string aGRCODEField;
        
        private string iTEMNOField;
        
        private string fILECODEField;
        
        private string fILENAMEField;
        
        private string fILETYPEField;
        
        private string fILEURLField;
        
        private string yL1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRCODE {
            get {
                return this.aGRCODEField;
            }
            set {
                this.aGRCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEMNO {
            get {
                return this.iTEMNOField;
            }
            set {
                this.iTEMNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILECODE {
            get {
                return this.fILECODEField;
            }
            set {
                this.fILECODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILENAME {
            get {
                return this.fILENAMEField;
            }
            set {
                this.fILENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILETYPE {
            get {
                return this.fILETYPEField;
            }
            set {
                this.fILETYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FILEURL {
            get {
                return this.fILEURLField;
            }
            set {
                this.fILEURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL1 {
            get {
                return this.yL1Field;
            }
            set {
                this.yL1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:zq:agreement")]
    public partial class DT_EC5_ZQ_IF001_REQAGREEMENTWZERPPRODUCTS {
        
        private string aGRCODEField;
        
        private string iTEMNOField;
        
        private string pRODNAMEField;
        
        private string pRODCLASSField;
        
        private string qUANTITYField;
        
        private string uNITField;
        
        private string pRICEField;
        
        private string tAXCODEField;
        
        private string yL1Field;
        
        private string yL2Field;
        
        private string yL3Field;
        
        private string yL4Field;
        
        private string yL5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRCODE {
            get {
                return this.aGRCODEField;
            }
            set {
                this.aGRCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEMNO {
            get {
                return this.iTEMNOField;
            }
            set {
                this.iTEMNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODNAME {
            get {
                return this.pRODNAMEField;
            }
            set {
                this.pRODNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODCLASS {
            get {
                return this.pRODCLASSField;
            }
            set {
                this.pRODCLASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRICE {
            get {
                return this.pRICEField;
            }
            set {
                this.pRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXCODE {
            get {
                return this.tAXCODEField;
            }
            set {
                this.tAXCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL1 {
            get {
                return this.yL1Field;
            }
            set {
                this.yL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL2 {
            get {
                return this.yL2Field;
            }
            set {
                this.yL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL3 {
            get {
                return this.yL3Field;
            }
            set {
                this.yL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL4 {
            get {
                return this.yL4Field;
            }
            set {
                this.yL4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YL5 {
            get {
                return this.yL5Field;
            }
            set {
                this.yL5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_WZERP_ZQ_IF001_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591