//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_ESR_CASH_FLOW_SPLIT {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_ESR_CASH_FLOW_SPLIT_A_OUTBinding", Namespace="urn:sinopec:ecc:fi:ecs")]
    public partial class SI_ESR_CASH_FLOW_SPLIT_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_ESR_CASH_FLOW_SPLIT_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_ESR_CASH_FLOW_SPLIT_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_ESR_CASH_FLOW_SPLIT_SI_ESR_CASH_FLOW_SPLIT_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_ESR_CASH_FLOW_SPLIT_A_OUTCompletedEventHandler SI_ESR_CASH_FLOW_SPLIT_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_ESR_CASH_FLOW_SPLIT_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ecc:fi:ecs")] DT_ERS_CASH_FLOW_SPLIT_REQ MT_ERS_CASH_FLOW_SPLIT_REQ) {
            this.Invoke("SI_ESR_CASH_FLOW_SPLIT_A_OUT", new object[] {
                        MT_ERS_CASH_FLOW_SPLIT_REQ});
        }
        
        /// <remarks/>
        public void SI_ESR_CASH_FLOW_SPLIT_A_OUTAsync(DT_ERS_CASH_FLOW_SPLIT_REQ MT_ERS_CASH_FLOW_SPLIT_REQ) {
            this.SI_ESR_CASH_FLOW_SPLIT_A_OUTAsync(MT_ERS_CASH_FLOW_SPLIT_REQ, null);
        }
        
        /// <remarks/>
        public void SI_ESR_CASH_FLOW_SPLIT_A_OUTAsync(DT_ERS_CASH_FLOW_SPLIT_REQ MT_ERS_CASH_FLOW_SPLIT_REQ, object userState) {
            if ((this.SI_ESR_CASH_FLOW_SPLIT_A_OUTOperationCompleted == null)) {
                this.SI_ESR_CASH_FLOW_SPLIT_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_ESR_CASH_FLOW_SPLIT_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_ESR_CASH_FLOW_SPLIT_A_OUT", new object[] {
                        MT_ERS_CASH_FLOW_SPLIT_REQ}, this.SI_ESR_CASH_FLOW_SPLIT_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_ESR_CASH_FLOW_SPLIT_A_OUTOperationCompleted(object arg) {
            if ((this.SI_ESR_CASH_FLOW_SPLIT_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_ESR_CASH_FLOW_SPLIT_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:ecc:fi:ecs")]
    public partial class DT_ERS_CASH_FLOW_SPLIT_REQ {
        
        private string iV_ZPZIDField;
        
        private string iV_ZECSIDField;
        
        private DT_ERS_CASH_FLOW_SPLIT_REQIT_ITEM[] iT_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_ZPZID {
            get {
                return this.iV_ZPZIDField;
            }
            set {
                this.iV_ZPZIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_ZECSID {
            get {
                return this.iV_ZECSIDField;
            }
            set {
                this.iV_ZECSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ERS_CASH_FLOW_SPLIT_REQIT_ITEM[] IT_ITEM {
            get {
                return this.iT_ITEMField;
            }
            set {
                this.iT_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:fi:ecs")]
    public partial class DT_ERS_CASH_FLOW_SPLIT_REQIT_ITEM {
        
        private string bUKRSField;
        
        private string bELNRField;
        
        private string gJAHRField;
        
        private string hKONTField;
        
        private string bELNR1Field;
        
        private string bUZEIField;
        
        private string bLARTField;
        
        private string bUDATField;
        
        private string mONATField;
        
        private string pRCTRField;
        
        private string gSBERField;
        
        private string vBUNDField;
        
        private string vCFLAGField;
        
        private string wAERSField;
        
        private string wRBTRField;
        
        private string hWAERField;
        
        private string dMBTRField;
        
        private string rSTGRField;
        
        private string tXT40Field;
        
        private string cCFLAGField;
        
        private string cCTXTField;
        
        private string uSNAMField;
        
        private string lIFNRField;
        
        private string sGTXTField;
        
        private string zUONRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BELNR {
            get {
                return this.bELNRField;
            }
            set {
                this.bELNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GJAHR {
            get {
                return this.gJAHRField;
            }
            set {
                this.gJAHRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HKONT {
            get {
                return this.hKONTField;
            }
            set {
                this.hKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BELNR1 {
            get {
                return this.bELNR1Field;
            }
            set {
                this.bELNR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUZEI {
            get {
                return this.bUZEIField;
            }
            set {
                this.bUZEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLART {
            get {
                return this.bLARTField;
            }
            set {
                this.bLARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUDAT {
            get {
                return this.bUDATField;
            }
            set {
                this.bUDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MONAT {
            get {
                return this.mONATField;
            }
            set {
                this.mONATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRCTR {
            get {
                return this.pRCTRField;
            }
            set {
                this.pRCTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GSBER {
            get {
                return this.gSBERField;
            }
            set {
                this.gSBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBUND {
            get {
                return this.vBUNDField;
            }
            set {
                this.vBUNDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VCFLAG {
            get {
                return this.vCFLAGField;
            }
            set {
                this.vCFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WRBTR {
            get {
                return this.wRBTRField;
            }
            set {
                this.wRBTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HWAER {
            get {
                return this.hWAERField;
            }
            set {
                this.hWAERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DMBTR {
            get {
                return this.dMBTRField;
            }
            set {
                this.dMBTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSTGR {
            get {
                return this.rSTGRField;
            }
            set {
                this.rSTGRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TXT40 {
            get {
                return this.tXT40Field;
            }
            set {
                this.tXT40Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CCFLAG {
            get {
                return this.cCFLAGField;
            }
            set {
                this.cCFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CCTXT {
            get {
                return this.cCTXTField;
            }
            set {
                this.cCTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USNAM {
            get {
                return this.uSNAMField;
            }
            set {
                this.uSNAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SGTXT {
            get {
                return this.sGTXTField;
            }
            set {
                this.sGTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZUONR {
            get {
                return this.zUONRField;
            }
            set {
                this.zUONRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_ESR_CASH_FLOW_SPLIT_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591