//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_WZERP_BID_TRANSFER {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_WZERP_BID_TRANSFER_REQ_A_OUTBinding", Namespace="urn:sinopec:ec5:bid:transfer")]
    public partial class SI_WZERP_BID_TRANSFER_REQ_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_WZERP_BID_TRANSFER_REQ_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_WZERP_BID_TRANSFER_REQ_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_WZERP_BID_TRANSFER_SI_WZERP_BID_TRANSFER_REQ_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_WZERP_BID_TRANSFER_REQ_A_OUTCompletedEventHandler SI_WZERP_BID_TRANSFER_REQ_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_WZERP_BID_TRANSFER_REQ_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ec5:bid:transfer")] DT_EC5_BID_TRANSFER_REQ MT_EC5_BID_TRANSFER_REQ) {
            this.Invoke("SI_WZERP_BID_TRANSFER_REQ_A_OUT", new object[] {
                        MT_EC5_BID_TRANSFER_REQ});
        }
        
        /// <remarks/>
        public void SI_WZERP_BID_TRANSFER_REQ_A_OUTAsync(DT_EC5_BID_TRANSFER_REQ MT_EC5_BID_TRANSFER_REQ) {
            this.SI_WZERP_BID_TRANSFER_REQ_A_OUTAsync(MT_EC5_BID_TRANSFER_REQ, null);
        }
        
        /// <remarks/>
        public void SI_WZERP_BID_TRANSFER_REQ_A_OUTAsync(DT_EC5_BID_TRANSFER_REQ MT_EC5_BID_TRANSFER_REQ, object userState) {
            if ((this.SI_WZERP_BID_TRANSFER_REQ_A_OUTOperationCompleted == null)) {
                this.SI_WZERP_BID_TRANSFER_REQ_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_WZERP_BID_TRANSFER_REQ_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_WZERP_BID_TRANSFER_REQ_A_OUT", new object[] {
                        MT_EC5_BID_TRANSFER_REQ}, this.SI_WZERP_BID_TRANSFER_REQ_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_WZERP_BID_TRANSFER_REQ_A_OUTOperationCompleted(object arg) {
            if ((this.SI_WZERP_BID_TRANSFER_REQ_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_WZERP_BID_TRANSFER_REQ_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:ec5:bid:transfer")]
    public partial class DT_EC5_BID_TRANSFER_REQ {
        
        private DT_EC5_BID_TRANSFER_REQBIDTRANSFER bIDTRANSFERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EC5_BID_TRANSFER_REQBIDTRANSFER BIDTRANSFER {
            get {
                return this.bIDTRANSFERField;
            }
            set {
                this.bIDTRANSFERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:bid:transfer")]
    public partial class DT_EC5_BID_TRANSFER_REQBIDTRANSFER {
        
        private string mSGIDField;
        
        private string sYSNUMERField;
        
        private string cOMPANYField;
        
        private string tRANSNUMField;
        
        private string dJTYPEField;
        
        private string bIDCONSIGNField;
        
        private string bIDFILECODEField;
        
        private string pACKIDField;
        
        private string pACKCODEField;
        
        private string zRBIDCONSIGNField;
        
        private string zRBIDFILECODEField;
        
        private string zRPACKIDField;
        
        private string zRPACKCODEField;
        
        private string sTRZBBMField;
        
        private string sTRCORPNAMEField;
        
        private string cURRENCYField;
        
        private string dJAMOUNTField;
        
        private string aMOUNTField;
        
        private string rEMARKField;
        
        private string dATUMField;
        
        private string uZEITField;
        
        private string rEALNAMEField;
        
        private string vOUCHERField;
        
        private string vOUCHERYEARField;
        
        private string zCZLXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SYSNUMER {
            get {
                return this.sYSNUMERField;
            }
            set {
                this.sYSNUMERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMPANY {
            get {
                return this.cOMPANYField;
            }
            set {
                this.cOMPANYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSNUM {
            get {
                return this.tRANSNUMField;
            }
            set {
                this.tRANSNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DJTYPE {
            get {
                return this.dJTYPEField;
            }
            set {
                this.dJTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDCONSIGN {
            get {
                return this.bIDCONSIGNField;
            }
            set {
                this.bIDCONSIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDFILECODE {
            get {
                return this.bIDFILECODEField;
            }
            set {
                this.bIDFILECODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKID {
            get {
                return this.pACKIDField;
            }
            set {
                this.pACKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKCODE {
            get {
                return this.pACKCODEField;
            }
            set {
                this.pACKCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRBIDCONSIGN {
            get {
                return this.zRBIDCONSIGNField;
            }
            set {
                this.zRBIDCONSIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRBIDFILECODE {
            get {
                return this.zRBIDFILECODEField;
            }
            set {
                this.zRBIDFILECODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRPACKID {
            get {
                return this.zRPACKIDField;
            }
            set {
                this.zRPACKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRPACKCODE {
            get {
                return this.zRPACKCODEField;
            }
            set {
                this.zRPACKCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRZBBM {
            get {
                return this.sTRZBBMField;
            }
            set {
                this.sTRZBBMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRCORPNAME {
            get {
                return this.sTRCORPNAMEField;
            }
            set {
                this.sTRCORPNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DJAMOUNT {
            get {
                return this.dJAMOUNTField;
            }
            set {
                this.dJAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATUM {
            get {
                return this.dATUMField;
            }
            set {
                this.dATUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UZEIT {
            get {
                return this.uZEITField;
            }
            set {
                this.uZEITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REALNAME {
            get {
                return this.rEALNAMEField;
            }
            set {
                this.rEALNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOUCHER {
            get {
                return this.vOUCHERField;
            }
            set {
                this.vOUCHERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOUCHERYEAR {
            get {
                return this.vOUCHERYEARField;
            }
            set {
                this.vOUCHERYEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCZLX {
            get {
                return this.zCZLXField;
            }
            set {
                this.zCZLXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_WZERP_BID_TRANSFER_REQ_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591