//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZERP_E_BUSINESS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_ERP_AGREEMENT_" +
            "A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Aagreement")]
        public string WZERP_E_BUSINESS_SI_EC5_ERP_AGREEMENT_SI_EC5_ERP_AGREEMENT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_ERP_AGREEMENT_SI_EC5_ERP_AGREEMENT_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_BID_PAYBACK_RE" +
            "Q_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Abid%3Apayment%3Ainfo")]
        public string WZERP_E_BUSINESS_SI_WZERP_BID_PAYBACK_SI_EC5_BID_PAYBACK_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_BID_PAYBACK_SI_EC5_BID_PAYBACK_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_ZQ_IF001_A_O" +
            "UT&interfaceNamespace=urn%3Asinopec%3Aec5%3Azq%3Aagreement")]
        public string WZERP_E_BUSINESS_SI_WZERP_ZQ_IF001_SI_WZERP_ZQ_IF001_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_ZQ_IF001_SI_WZERP_ZQ_IF001_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_STOCK_AUTHORIZ" +
            "E_REQ_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Apurchase%3Acontrol%" +
            "3Aintegration")]
        public string WZERP_E_BUSINESS_SI_EC5_STOCK_AUTHORIZE_SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_STOCK_AUTHORIZE_SI_EC5_STOCK_AUTHORIZE_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_CONTRACT_INVOI" +
            "CE_RESULT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_ERP_CONTRACT_INVOICE_RESULT_SI_EC5_CONTRACT_INVOICE_RESULT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_ERP_CONTRACT_INVOICE_RESULT_SI_EC5_CONTRACT_INVOICE_RESULT_A_" +
                    "OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_CONTRACT_PAID_" +
            "RESULT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_ERP_CONTRACT_PAID_RESULT_SI_EC5_CONTRACT_PAID_RESULT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_ERP_CONTRACT_PAID_RESULT_SI_EC5_CONTRACT_PAID_RESULT_A_OUTSer" +
                    "vice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_ZQ_IF002_A_O" +
            "UT&interfaceNamespace=urn%3Asinopec%3Aec5%3Azq%3Aagreement")]
        public string WZERP_E_BUSINESS_SI_WZERP_ZQ_IF002_SI_WZERP_ZQ_IF002_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_ZQ_IF002_SI_WZERP_ZQ_IF002_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_STOCK_AFFRIM_R" +
            "EQ_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Apurchase%3Acontrol%3Ai" +
            "ntegration")]
        public string WZERP_E_BUSINESS_SI_EC5_STOCK_AFFRIM_SI_EC5_STOCK_AFFRIM_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_STOCK_AFFRIM_SI_EC5_STOCK_AFFRIM_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_AGREEMENT_TE" +
            "XT_RESULT_A_OUT&interfaceNamespace=urn%3Asinopec%3Awzerp%3Aec5%3Aagreement%3Atex" +
            "t")]
        public string WZERP_E_BUSINESS_SI_WZERP_AGREEMENT_TEXT_RESULT_SI_WZERP_AGREEMENT_TEXT_RESULT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_AGREEMENT_TEXT_RESULT_SI_WZERP_AGREEMENT_TEXT_RESULT_A_" +
                    "OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_WZERP_PAY_CONT" +
            "RACT_RESP_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_EC5_WZERP_PAY_CONTRACT_RESP_SI_EC5_WZERP_PAY_CONTRACT_RESP_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_WZERP_PAY_CONTRACT_RESP_SI_EC5_WZERP_PAY_CONTRACT_RESP_A_" +
                    "OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_ZQ_IF006_RES" +
            "P_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Azq%3Aagreement")]
        public string WZERP_E_BUSINESS_SI_WZERP_ZQ_IF006_RESP_SI_WZERP_ZQ_IF006_RESP_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_ZQ_IF006_RESP_SI_WZERP_ZQ_IF006_RESP_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_LOGISTICS_INFO" +
            "_RESULT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Alogistics%3Ainfo")]
        public string WZERP_E_BUSINESS_SI_EC5_LOGISTICS_INFO_RESULT_SI_EC5_LOGISTICS_INFO_RESULT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_LOGISTICS_INFO_RESULT_SI_EC5_LOGISTICS_INFO_RESULT_A_OUTS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_WZERP_PR_REQ_A" +
            "_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Apurchase%3Acontrol%3Ainteg" +
            "ration")]
        public string WZERP_E_BUSINESS_SI_EC5_WZERP_PR_REQ_SI_EC5_WZERP_PR_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_WZERP_PR_REQ_SI_EC5_WZERP_PR_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_PURCHASE_AMOUN" +
            "T_RESP_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Apurchase%3Acontrol" +
            "%3Aintegration")]
        public string WZERP_E_BUSINESS_SI_WZERP_PURCHASE_AMOUNT_SI_EC5_PURCHASE_AMOUNT_RESP_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_PURCHASE_AMOUNT_SI_EC5_PURCHASE_AMOUNT_RESP_A_OUTServic" +
                    "e"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_BID_REFUND_REQ" +
            "_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Abid%3Apayment%3Ainfo")]
        public string WZERP_E_BUSINESS_SI_WZERP_BID_REFUND_SI_EC5_BID_REFUND_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_BID_REFUND_SI_EC5_BID_REFUND_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_BID_TRANSFER" +
            "_REQ_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Abid%3Atransfer")]
        public string WZERP_E_BUSINESS_SI_WZERP_BID_TRANSFER_SI_WZERP_BID_TRANSFER_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_BID_TRANSFER_SI_WZERP_BID_TRANSFER_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_WZERP_CONTRACT" +
            "_REQ_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_EC5_ERP_CONTRACT_REQ_SI_EC5_WZERP_CONTRACT_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_ERP_CONTRACT_REQ_SI_EC5_WZERP_CONTRACT_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_LOGISTICS_CONT" +
            "RACT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_EC5_ERP_LOGISTICS_CONTRACT_SI_EC5_LOGISTICS_CONTRACT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_ERP_LOGISTICS_CONTRACT_SI_EC5_LOGISTICS_CONTRACT_A_OUTSer" +
                    "vice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_CONTRACT_CLOSE" +
            "D_RESULT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_ERP_CONTRACT_CLOSED_RESULT_SI_EC5_CONTRACT_CLOSED_RESULT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_ERP_CONTRACT_CLOSED_RESULT_SI_EC5_CONTRACT_CLOSED_RESULT_A_OU" +
                    "TService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_WZERP_CONTRACT" +
            "_REQ_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_EC5_ERP_CONTRACT_REQ1_SI_EC5_WZERP_CONTRACT_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_ERP_CONTRACT_REQ1_SI_EC5_WZERP_CONTRACT_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_LOGISTICS_CONT" +
            "RACT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_EC5_ERP_LOGISTICS_CONTRACT1_SI_EC5_LOGISTICS_CONTRACT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_ERP_LOGISTICS_CONTRACT1_SI_EC5_LOGISTICS_CONTRACT_A_OUTSe" +
                    "rvice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_CONTRACT_CLOSE" +
            "D_RESULT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Awzerp%3Acontract")]
        public string WZERP_E_BUSINESS_SI_ERP_CONTRACT_CLOSED_RESULT_A_IN_SI_EC5_CONTRACT_CLOSED_RESULT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_ERP_CONTRACT_CLOSED_RESULT_A_IN_SI_EC5_CONTRACT_CLOSED_RESULT" +
                    "_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_ZQ_IF003_A_O" +
            "UT&interfaceNamespace=urn%3Asinopec%3Aec5%3Azq%3Aagreement")]
        public string WZERP_E_BUSINESS_SI_WZERP_ZQ_IF003_SI_WZERP_ZQ_IF003_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_ZQ_IF003_SI_WZERP_ZQ_IF003_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_ZQ_IF004_A_O" +
            "UT&interfaceNamespace=urn%3Asinopec%3Aec5%3Azq%3Aagreement")]
        public string WZERP_E_BUSINESS_SI_WZERP_ZQ_IF004_SI_WZERP_ZQ_IF004_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_ZQ_IF004_SI_WZERP_ZQ_IF004_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_WZERP_ZQ_IF005_A_O" +
            "UT&interfaceNamespace=urn%3Asinopec%3Aec5%3Azq%3Aagreement")]
        public string WZERP_E_BUSINESS_SI_WZERP_ZQ_IF005_SI_WZERP_ZQ_IF005_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_ZQ_IF005_SI_WZERP_ZQ_IF005_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_IDEC_QAS&receiverParty=&receiverService=&interface=SI_EPEC_ORDER_CLOSE_" +
            "RESP_A_OUT&interfaceNamespace=urn%3Asinopec%3Aecc%3Awzerp%3Aepec%3Aintegration")]
        public string WZERP_E_BUSINESS_SI_EPEC_ORDER_CLOSE_RESP_SI_EPEC_ORDER_CLOSE_RESP_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EPEC_ORDER_CLOSE_RESP_SI_EPEC_ORDER_CLOSE_RESP_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_IDEC_QAS&receiverParty=&receiverService=&interface=SI_EPEC_DO_POST_RESP" +
            "_A_OUT&interfaceNamespace=urn%3Asinopec%3Aecc%3Awzerp%3Aepec%3Aintegration")]
        public string WZERP_E_BUSINESS_SI_EPEC_DO_POST_RESP1_SI_EPEC_DO_POST_RESP_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EPEC_DO_POST_RESP1_SI_EPEC_DO_POST_RESP_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_IDEC_QAS&receiverParty=&receiverService=&interface=SI_EPEC_ORDER_APP_RE" +
            "SP_A_OUT&interfaceNamespace=urn%3Asinopec%3Aecc%3Awzerp%3Aepec%3Aintegration")]
        public string WZERP_E_BUSINESS_SI_EPEC_ORDER_APP_RESP_SI_EPEC_ORDER_APP_RESP_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EPEC_ORDER_APP_RESP_SI_EPEC_ORDER_APP_RESP_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_IDEC_QAS&receiverParty=&receiverService=&interface=SI_IDEC_EMARKET_PO_C" +
            "ONFIRM_A_OUT&interfaceNamespace=urn%3Asinopec%3Aecc%3Amm%3Aidec_mro")]
        public string WZERP_E_BUSINESS_SI_IDEC_EMARKET_PO_CONFIRM_SI_IDEC_EMARKET_PO_CONFIRM_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_IDEC_EMARKET_PO_CONFIRM_SI_IDEC_EMARKET_PO_CONFIRM_A_OUTServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_IDEC_QAS&receiverParty=&receiverService=&interface=SI_WZERP_PAYBACK_RES" +
            "ULT_A_OUT&interfaceNamespace=urn%3Asinopec%3Aecc%3Awzerp%3Aepec%3Aintegration")]
        public string WZERP_E_BUSINESS_SI_WZERP_PAYBACK_RESULT1_SI_WZERP_PAYBACK_RESULT_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_WZERP_PAYBACK_RESULT1_SI_WZERP_PAYBACK_RESULT_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_IDEC_QAS&receiverParty=&receiverService=&interface=SI_IDEC_PO2ECC_REQ_A" +
            "_OUT&interfaceNamespace=urn%3Asinopec%3Aecc%3Amm%3Aidec_mro")]
        public string WZERP_E_BUSINESS_SI_IDEC_PO2ECC_REQ_A_SI_IDEC_PO2ECC_REQ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_IDEC_PO2ECC_REQ_A_SI_IDEC_PO2ECC_REQ_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_IDEC_QAS&receiverParty=&receiverService=&interface=SI_EPEC_PO_JSJZ_RESP" +
            "_A_OUT&interfaceNamespace=urn%3Asinopec%3Aecc%3Awzerp%3Aepec%3Aintegration")]
        public string WZERP_E_BUSINESS_SI_EPEC_PO_JSJZ_RESP_SI_EPEC_PO_JSJZ_RESP_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EPEC_PO_JSJZ_RESP_SI_EPEC_PO_JSJZ_RESP_A_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hqxt1.sinopec.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderSe" +
            "rvice=BS_EC5_QAS&receiverParty=&receiverService=&interface=SI_EC5_DISPATCH_SO_RE" +
            "Q_DJZ_A_OUT&interfaceNamespace=urn%3Asinopec%3Aec5%3Adispatch%3Aso%3Arequest")]
        public string WZERP_E_BUSINESS_SI_EC5_DISPATCH_SO_REQ_DJZ_SI_EC5_DISPATCH_SO_REQ_DJZ_A_OUTService {
            get {
                return ((string)(this["WZERP_E_BUSINESS_SI_EC5_DISPATCH_SO_REQ_DJZ_SI_EC5_DISPATCH_SO_REQ_DJZ_A_OUTServi" +
                    "ce"]));
            }
        }
    }
}
