//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_EC5_ERP_CONTRACT_REQ1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_EC5_WZERP_CONTRACT_REQ_A_OUTBinding", Namespace="urn:sinopec:ec5:wzerp:contract")]
    public partial class SI_EC5_WZERP_CONTRACT_REQ_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_EC5_WZERP_CONTRACT_REQ_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_EC5_WZERP_CONTRACT_REQ_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_EC5_ERP_CONTRACT_REQ1_SI_EC5_WZERP_CONTRACT_REQ_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_EC5_WZERP_CONTRACT_REQ_A_OUTCompletedEventHandler SI_EC5_WZERP_CONTRACT_REQ_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_EC5_WZERP_CONTRACT_REQ_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ec5:wzerp:contract")] CONTRACT CONTRACT) {
            this.Invoke("SI_EC5_WZERP_CONTRACT_REQ_A_OUT", new object[] {
                        CONTRACT});
        }
        
        /// <remarks/>
        public void SI_EC5_WZERP_CONTRACT_REQ_A_OUTAsync(CONTRACT CONTRACT) {
            this.SI_EC5_WZERP_CONTRACT_REQ_A_OUTAsync(CONTRACT, null);
        }
        
        /// <remarks/>
        public void SI_EC5_WZERP_CONTRACT_REQ_A_OUTAsync(CONTRACT CONTRACT, object userState) {
            if ((this.SI_EC5_WZERP_CONTRACT_REQ_A_OUTOperationCompleted == null)) {
                this.SI_EC5_WZERP_CONTRACT_REQ_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_EC5_WZERP_CONTRACT_REQ_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_EC5_WZERP_CONTRACT_REQ_A_OUT", new object[] {
                        CONTRACT}, this.SI_EC5_WZERP_CONTRACT_REQ_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_EC5_WZERP_CONTRACT_REQ_A_OUTOperationCompleted(object arg) {
            if ((this.SI_EC5_WZERP_CONTRACT_REQ_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_EC5_WZERP_CONTRACT_REQ_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:wzerp:contract")]
    public partial class CONTRACT {
        
        private string mSGIDField;
        
        private string sTRSYSNUMBERField;
        
        private string pONOField;
        
        private string eCPONOField;
        
        private string sUPPCODEField;
        
        private string vENDORCODEField;
        
        private string cORPCODEField;
        
        private string cORPCODEN4Field;
        
        private string eRPGROUPField;
        
        private string cREATEUSERField;
        
        private string iNTPFZCField;
        
        private string dASUBTIMEField;
        
        private string kONNRField;
        
        private string aTTRTYPEField;
        
        private string sTOCKTYPEField;
        
        private string eNQUTYPEField;
        
        private string cREATEDATEField;
        
        private string iSPOField;
        
        private string oUTPORTField;
        
        private string aRRIVEPORTField;
        
        private string dOWNLOADDATEField;
        
        private string iFLAGField;
        
        private CONTRACTCONTRACTMAT[] cONTRACTMATField;

        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRSYSNUMBER {
            get {
                return this.sTRSYSNUMBERField;
            }
            set {
                this.sTRSYSNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PONO {
            get {
                return this.pONOField;
            }
            set {
                this.pONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ECPONO {
            get {
                return this.eCPONOField;
            }
            set {
                this.eCPONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUPPCODE {
            get {
                return this.sUPPCODEField;
            }
            set {
                this.sUPPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDORCODE {
            get {
                return this.vENDORCODEField;
            }
            set {
                this.vENDORCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPCODE {
            get {
                return this.cORPCODEField;
            }
            set {
                this.cORPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPCODEN4 {
            get {
                return this.cORPCODEN4Field;
            }
            set {
                this.cORPCODEN4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPGROUP {
            get {
                return this.eRPGROUPField;
            }
            set {
                this.eRPGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATEUSER {
            get {
                return this.cREATEUSERField;
            }
            set {
                this.cREATEUSERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTPFZC {
            get {
                return this.iNTPFZCField;
            }
            set {
                this.iNTPFZCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DASUBTIME {
            get {
                return this.dASUBTIMEField;
            }
            set {
                this.dASUBTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KONNR {
            get {
                return this.kONNRField;
            }
            set {
                this.kONNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTRTYPE {
            get {
                return this.aTTRTYPEField;
            }
            set {
                this.aTTRTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCKTYPE {
            get {
                return this.sTOCKTYPEField;
            }
            set {
                this.sTOCKTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENQUTYPE {
            get {
                return this.eNQUTYPEField;
            }
            set {
                this.eNQUTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATEDATE {
            get {
                return this.cREATEDATEField;
            }
            set {
                this.cREATEDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ISPO {
            get {
                return this.iSPOField;
            }
            set {
                this.iSPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OUTPORT {
            get {
                return this.oUTPORTField;
            }
            set {
                this.oUTPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ARRIVEPORT {
            get {
                return this.aRRIVEPORTField;
            }
            set {
                this.aRRIVEPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOWNLOADDATE {
            get {
                return this.dOWNLOADDATEField;
            }
            set {
                this.dOWNLOADDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IFLAG {
            get {
                return this.iFLAGField;
            }
            set {
                this.iFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONTRACTMAT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CONTRACTCONTRACTMAT[] CONTRACTMAT {
            get {
                return this.cONTRACTMATField;
            }
            set {
                this.cONTRACTMATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:wzerp:contract")]
    public partial class CONTRACTCONTRACTMAT {
        
        private string eCORDERCODEField;
        
        private string cORPCODEField;
        
        private string pRODCODEField;
        
        private string pRNOField;
        
        private string pRODDESCField;
        
        private string iNTQTYField;
        
        private string iNTPRICEField;
        
        private string iNTFREEField;
        
        private string iNTOTHERField;
        
        private string sAVEAMOUNTField;
        
        private string tAXCODEField;
        
        private string iNTAVGPRICEField;
        
        private string uNITField;
        
        private string cONTADDField;
        
        private string tECHSTANDARDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ECORDERCODE {
            get {
                return this.eCORDERCODEField;
            }
            set {
                this.eCORDERCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPCODE {
            get {
                return this.cORPCODEField;
            }
            set {
                this.cORPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODCODE {
            get {
                return this.pRODCODEField;
            }
            set {
                this.pRODCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRNO {
            get {
                return this.pRNOField;
            }
            set {
                this.pRNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODDESC {
            get {
                return this.pRODDESCField;
            }
            set {
                this.pRODDESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTQTY {
            get {
                return this.iNTQTYField;
            }
            set {
                this.iNTQTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTPRICE {
            get {
                return this.iNTPRICEField;
            }
            set {
                this.iNTPRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTFREE {
            get {
                return this.iNTFREEField;
            }
            set {
                this.iNTFREEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTOTHER {
            get {
                return this.iNTOTHERField;
            }
            set {
                this.iNTOTHERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAVEAMOUNT {
            get {
                return this.sAVEAMOUNTField;
            }
            set {
                this.sAVEAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXCODE {
            get {
                return this.tAXCODEField;
            }
            set {
                this.tAXCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTAVGPRICE {
            get {
                return this.iNTAVGPRICEField;
            }
            set {
                this.iNTAVGPRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTADD {
            get {
                return this.cONTADDField;
            }
            set {
                this.cONTADDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TECHSTANDARD {
            get {
                return this.tECHSTANDARDField;
            }
            set {
                this.tECHSTANDARDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_EC5_WZERP_CONTRACT_REQ_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591