//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_EC5_ERP_AGREEMENT {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_EC5_ERP_AGREEMENT_A_OUTBinding", Namespace="urn:sinopec:ec5:agreement")]
    public partial class SI_EC5_ERP_AGREEMENT_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_EC5_ERP_AGREEMENT_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_EC5_ERP_AGREEMENT_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_EC5_ERP_AGREEMENT_SI_EC5_ERP_AGREEMENT_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_EC5_ERP_AGREEMENT_A_OUTCompletedEventHandler SI_EC5_ERP_AGREEMENT_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_EC5_ERP_AGREEMENT_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ec5:agreement")] AGREEMENT AGREEMENT) {
            this.Invoke("SI_EC5_ERP_AGREEMENT_A_OUT", new object[] {
                        AGREEMENT});
        }
        
        /// <remarks/>
        public void SI_EC5_ERP_AGREEMENT_A_OUTAsync(AGREEMENT AGREEMENT) {
            this.SI_EC5_ERP_AGREEMENT_A_OUTAsync(AGREEMENT, null);
        }
        
        /// <remarks/>
        public void SI_EC5_ERP_AGREEMENT_A_OUTAsync(AGREEMENT AGREEMENT, object userState) {
            if ((this.SI_EC5_ERP_AGREEMENT_A_OUTOperationCompleted == null)) {
                this.SI_EC5_ERP_AGREEMENT_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_EC5_ERP_AGREEMENT_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_EC5_ERP_AGREEMENT_A_OUT", new object[] {
                        AGREEMENT}, this.SI_EC5_ERP_AGREEMENT_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_EC5_ERP_AGREEMENT_A_OUTOperationCompleted(object arg) {
            if ((this.SI_EC5_ERP_AGREEMENT_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_EC5_ERP_AGREEMENT_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:agreement")]
    public partial class AGREEMENT {
        
        private string mSGIDField;
        
        private string sTRNField;
        
        private string aGRCODEField;
        
        private string aGRNAMEField;
        
        private string aGRPROJCODEField;
        
        private string sIGNTYPEField;
        
        private string aGRVERSIONField;
        
        private string aGRCONTRACTCODEField;
        
        private string aGREETYPEField;
        
        private string cREATECORPField;
        
        private string cREATEDEPTField;
        
        private string sIGNDATEField;
        
        private string sIGNUSERField;
        
        private string sIGNSUPPField;
        
        private string sIGNSUPPNAMEField;
        
        private string sUPPQUOTAField;
        
        private string sTARTDATEField;
        
        private string eNDDATEField;
        
        private string sUBTIMEField;
        
        private string sENDTIMEField;
        
        private string sTOCKTYPEField;
        
        private string bIDCODEField;
        
        private string aTTRTYPEField;
        
        private string iNTTYPEField;
        
        private string aTTACHMENTURLField;
        
        private string rEMARKTEXTField;
        
        private string pROJCODEField;
        
        private string sTOCKAFFCODEField;
        
        private string tAXRATEField;
        
        private string tARGETVALUEField;
        
        private string cURRENCYField;
        
        private string sAVINGRATEField;
        
        private AGREEMENTAgreementENT[] agreementENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRN {
            get {
                return this.sTRNField;
            }
            set {
                this.sTRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRCODE {
            get {
                return this.aGRCODEField;
            }
            set {
                this.aGRCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRNAME {
            get {
                return this.aGRNAMEField;
            }
            set {
                this.aGRNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRPROJCODE {
            get {
                return this.aGRPROJCODEField;
            }
            set {
                this.aGRPROJCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGNTYPE {
            get {
                return this.sIGNTYPEField;
            }
            set {
                this.sIGNTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRVERSION {
            get {
                return this.aGRVERSIONField;
            }
            set {
                this.aGRVERSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGRCONTRACTCODE {
            get {
                return this.aGRCONTRACTCODEField;
            }
            set {
                this.aGRCONTRACTCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AGREETYPE {
            get {
                return this.aGREETYPEField;
            }
            set {
                this.aGREETYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATECORP {
            get {
                return this.cREATECORPField;
            }
            set {
                this.cREATECORPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREATEDEPT {
            get {
                return this.cREATEDEPTField;
            }
            set {
                this.cREATEDEPTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGNDATE {
            get {
                return this.sIGNDATEField;
            }
            set {
                this.sIGNDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGNUSER {
            get {
                return this.sIGNUSERField;
            }
            set {
                this.sIGNUSERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGNSUPP {
            get {
                return this.sIGNSUPPField;
            }
            set {
                this.sIGNSUPPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SIGNSUPPNAME {
            get {
                return this.sIGNSUPPNAMEField;
            }
            set {
                this.sIGNSUPPNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUPPQUOTA {
            get {
                return this.sUPPQUOTAField;
            }
            set {
                this.sUPPQUOTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STARTDATE {
            get {
                return this.sTARTDATEField;
            }
            set {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUBTIME {
            get {
                return this.sUBTIMEField;
            }
            set {
                this.sUBTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SENDTIME {
            get {
                return this.sENDTIMEField;
            }
            set {
                this.sENDTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCKTYPE {
            get {
                return this.sTOCKTYPEField;
            }
            set {
                this.sTOCKTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDCODE {
            get {
                return this.bIDCODEField;
            }
            set {
                this.bIDCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTRTYPE {
            get {
                return this.aTTRTYPEField;
            }
            set {
                this.aTTRTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTTYPE {
            get {
                return this.iNTTYPEField;
            }
            set {
                this.iNTTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTACHMENTURL {
            get {
                return this.aTTACHMENTURLField;
            }
            set {
                this.aTTACHMENTURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMARKTEXT {
            get {
                return this.rEMARKTEXTField;
            }
            set {
                this.rEMARKTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROJCODE {
            get {
                return this.pROJCODEField;
            }
            set {
                this.pROJCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOCKAFFCODE {
            get {
                return this.sTOCKAFFCODEField;
            }
            set {
                this.sTOCKAFFCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXRATE {
            get {
                return this.tAXRATEField;
            }
            set {
                this.tAXRATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARGETVALUE {
            get {
                return this.tARGETVALUEField;
            }
            set {
                this.tARGETVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAVINGRATE {
            get {
                return this.sAVINGRATEField;
            }
            set {
                this.sAVINGRATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AgreementENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AGREEMENTAgreementENT[] AgreementENT {
            get {
                return this.agreementENTField;
            }
            set {
                this.agreementENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:agreement")]
    public partial class AGREEMENTAgreementENT {
        
        private string cORPCODEField;
        
        private string cORPNAMEField;
        
        private string cORPTYPEField;
        
        private string eRPORGField;
        
        private string eRPGROUPField;
        
        private string eRPGROUPNAMEField;
        
        private string eRPFACTORYField;
        
        private string eRPFACTORYNAMEField;
        
        private string cORPAMOUNTField;
        
        private string cORPTARGETVALUEField;
        
        private AGREEMENTAgreementENTAgreementMAT[] agreementMATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPCODE {
            get {
                return this.cORPCODEField;
            }
            set {
                this.cORPCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPNAME {
            get {
                return this.cORPNAMEField;
            }
            set {
                this.cORPNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPTYPE {
            get {
                return this.cORPTYPEField;
            }
            set {
                this.cORPTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPORG {
            get {
                return this.eRPORGField;
            }
            set {
                this.eRPORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPGROUP {
            get {
                return this.eRPGROUPField;
            }
            set {
                this.eRPGROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPGROUPNAME {
            get {
                return this.eRPGROUPNAMEField;
            }
            set {
                this.eRPGROUPNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPFACTORY {
            get {
                return this.eRPFACTORYField;
            }
            set {
                this.eRPFACTORYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPFACTORYNAME {
            get {
                return this.eRPFACTORYNAMEField;
            }
            set {
                this.eRPFACTORYNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPAMOUNT {
            get {
                return this.cORPAMOUNTField;
            }
            set {
                this.cORPAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORPTARGETVALUE {
            get {
                return this.cORPTARGETVALUEField;
            }
            set {
                this.cORPTARGETVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AgreementMAT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AGREEMENTAgreementENTAgreementMAT[] AgreementMAT {
            get {
                return this.agreementMATField;
            }
            set {
                this.agreementMATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:agreement")]
    public partial class AGREEMENTAgreementENTAgreementMAT {
        
        private string iTEMNOField;
        
        private string iTEMTYPEField;
        
        private string pRODCLASSField;
        
        private string pRODCODEField;
        
        private string pRODNAMEField;
        
        private string uNITField;
        
        private string eRPUNITField;
        
        private string qUANTITYField;
        
        private string pRICEField;
        
        private string aVGPRICEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEMNO {
            get {
                return this.iTEMNOField;
            }
            set {
                this.iTEMNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEMTYPE {
            get {
                return this.iTEMTYPEField;
            }
            set {
                this.iTEMTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODCLASS {
            get {
                return this.pRODCLASSField;
            }
            set {
                this.pRODCLASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODCODE {
            get {
                return this.pRODCODEField;
            }
            set {
                this.pRODCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODNAME {
            get {
                return this.pRODNAMEField;
            }
            set {
                this.pRODNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERPUNIT {
            get {
                return this.eRPUNITField;
            }
            set {
                this.eRPUNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRICE {
            get {
                return this.pRICEField;
            }
            set {
                this.pRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AVGPRICE {
            get {
                return this.aVGPRICEField;
            }
            set {
                this.aVGPRICEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_EC5_ERP_AGREEMENT_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591