//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_WZERP_BID_PAYBACK {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_EC5_BID_PAYBACK_REQ_A_OUTBinding", Namespace="urn:sinopec:ec5:wzerp:bid:payment:info")]
    public partial class SI_EC5_BID_PAYBACK_REQ_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_EC5_BID_PAYBACK_REQ_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_EC5_BID_PAYBACK_REQ_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_WZERP_BID_PAYBACK_SI_EC5_BID_PAYBACK_REQ_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_EC5_BID_PAYBACK_REQ_A_OUTCompletedEventHandler SI_EC5_BID_PAYBACK_REQ_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_EC5_BID_PAYBACK_REQ_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ec5:wzerp:bid:payment:info")] DT_EC5_BID_PAYBACK_REQUEST BIDPAYBACK) {
            this.Invoke("SI_EC5_BID_PAYBACK_REQ_A_OUT", new object[] {
                        BIDPAYBACK});
        }
        
        /// <remarks/>
        public void SI_EC5_BID_PAYBACK_REQ_A_OUTAsync(DT_EC5_BID_PAYBACK_REQUEST BIDPAYBACK) {
            this.SI_EC5_BID_PAYBACK_REQ_A_OUTAsync(BIDPAYBACK, null);
        }
        
        /// <remarks/>
        public void SI_EC5_BID_PAYBACK_REQ_A_OUTAsync(DT_EC5_BID_PAYBACK_REQUEST BIDPAYBACK, object userState) {
            if ((this.SI_EC5_BID_PAYBACK_REQ_A_OUTOperationCompleted == null)) {
                this.SI_EC5_BID_PAYBACK_REQ_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_EC5_BID_PAYBACK_REQ_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_EC5_BID_PAYBACK_REQ_A_OUT", new object[] {
                        BIDPAYBACK}, this.SI_EC5_BID_PAYBACK_REQ_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_EC5_BID_PAYBACK_REQ_A_OUTOperationCompleted(object arg) {
            if ((this.SI_EC5_BID_PAYBACK_REQ_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_EC5_BID_PAYBACK_REQ_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:ec5:wzerp:bid:payment:info")]
    public partial class DT_EC5_BID_PAYBACK_REQUEST {
        
        private string mSGIDField;
        
        private string sYSNUMERField;
        
        private string cOMPANYField;
        
        private string zHKWYHField;
        
        private string bIDCONSIGNField;
        
        private string bIDFILECODEField;
        
        private string gOODSField;
        
        private string iTEMCODEField;
        
        private string iTEMNAMEField;
        
        private string sTRZBBMField;
        
        private string sTRCORPNAMEField;
        
        private string bILLDOCNUMField;
        
        private string aCCOUNTNAMEField;
        
        private string bANKNAMEField;
        
        private string aCCOUNTNUMField;
        
        private string aCCEPTBANKField;
        
        private string tOTALAMOUNTField;
        
        private string cURRENCYField;
        
        private string rATEField;
        
        private string oPERATETYPEField;
        
        private string dATUMField;
        
        private string rEALNAMEField;
        
        private string zZFPTField;
        
        private string tEXCODEField;
        
        private string bANKField;
        
        private string aCCOUNTNOField;
        
        private string aDDRESSField;
        
        private string tELField;
        
        private string zDZYXField;
        
        private string mOBILEField;
        
        private string zBYZD1Field;
        
        private string zBYZD2Field;
        
        private string zBYZD3Field;
        
        private string zBYZD4Field;
        
        private string zBYZD5Field;
        
        private DT_EC5_BID_PAYBACK_REQUESTBIDPAYBACKMAT[] bIDPAYBACKMATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SYSNUMER {
            get {
                return this.sYSNUMERField;
            }
            set {
                this.sYSNUMERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMPANY {
            get {
                return this.cOMPANYField;
            }
            set {
                this.cOMPANYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZHKWYH {
            get {
                return this.zHKWYHField;
            }
            set {
                this.zHKWYHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDCONSIGN {
            get {
                return this.bIDCONSIGNField;
            }
            set {
                this.bIDCONSIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BIDFILECODE {
            get {
                return this.bIDFILECODEField;
            }
            set {
                this.bIDFILECODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GOODS {
            get {
                return this.gOODSField;
            }
            set {
                this.gOODSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEMCODE {
            get {
                return this.iTEMCODEField;
            }
            set {
                this.iTEMCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEMNAME {
            get {
                return this.iTEMNAMEField;
            }
            set {
                this.iTEMNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRZBBM {
            get {
                return this.sTRZBBMField;
            }
            set {
                this.sTRZBBMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRCORPNAME {
            get {
                return this.sTRCORPNAMEField;
            }
            set {
                this.sTRCORPNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILLDOCNUM {
            get {
                return this.bILLDOCNUMField;
            }
            set {
                this.bILLDOCNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTNAME {
            get {
                return this.aCCOUNTNAMEField;
            }
            set {
                this.aCCOUNTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKNAME {
            get {
                return this.bANKNAMEField;
            }
            set {
                this.bANKNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTNUM {
            get {
                return this.aCCOUNTNUMField;
            }
            set {
                this.aCCOUNTNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCEPTBANK {
            get {
                return this.aCCEPTBANKField;
            }
            set {
                this.aCCEPTBANKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALAMOUNT {
            get {
                return this.tOTALAMOUNTField;
            }
            set {
                this.tOTALAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPERATETYPE {
            get {
                return this.oPERATETYPEField;
            }
            set {
                this.oPERATETYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATUM {
            get {
                return this.dATUMField;
            }
            set {
                this.dATUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REALNAME {
            get {
                return this.rEALNAMEField;
            }
            set {
                this.rEALNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZFPT {
            get {
                return this.zZFPTField;
            }
            set {
                this.zZFPTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXCODE {
            get {
                return this.tEXCODEField;
            }
            set {
                this.tEXCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANK {
            get {
                return this.bANKField;
            }
            set {
                this.bANKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ACCOUNTNO {
            get {
                return this.aCCOUNTNOField;
            }
            set {
                this.aCCOUNTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRESS {
            get {
                return this.aDDRESSField;
            }
            set {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEL {
            get {
                return this.tELField;
            }
            set {
                this.tELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZDZYX {
            get {
                return this.zDZYXField;
            }
            set {
                this.zDZYXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MOBILE {
            get {
                return this.mOBILEField;
            }
            set {
                this.mOBILEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBYZD1 {
            get {
                return this.zBYZD1Field;
            }
            set {
                this.zBYZD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBYZD2 {
            get {
                return this.zBYZD2Field;
            }
            set {
                this.zBYZD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBYZD3 {
            get {
                return this.zBYZD3Field;
            }
            set {
                this.zBYZD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBYZD4 {
            get {
                return this.zBYZD4Field;
            }
            set {
                this.zBYZD4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBYZD5 {
            get {
                return this.zBYZD5Field;
            }
            set {
                this.zBYZD5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BIDPAYBACKMAT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EC5_BID_PAYBACK_REQUESTBIDPAYBACKMAT[] BIDPAYBACKMAT {
            get {
                return this.bIDPAYBACKMATField;
            }
            set {
                this.bIDPAYBACKMATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:wzerp:bid:payment:info")]
    public partial class DT_EC5_BID_PAYBACK_REQUESTBIDPAYBACKMAT {
        
        private string lINEITEMField;
        
        private string fUNDTYPEField;
        
        private string zFPLXField;
        
        private string iNVOICENOField;
        
        private string oRDERNOField;
        
        private string pACKCODEField;
        
        private string aMOUNTField;
        
        private string dEPOSITField;
        
        private string rEMARKField;
        
        private DT_EC5_BID_PAYBACK_REQUESTBIDPAYBACKMATVOUCHER[] vOUCHERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINEITEM {
            get {
                return this.lINEITEMField;
            }
            set {
                this.lINEITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FUNDTYPE {
            get {
                return this.fUNDTYPEField;
            }
            set {
                this.fUNDTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZFPLX {
            get {
                return this.zFPLXField;
            }
            set {
                this.zFPLXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INVOICENO {
            get {
                return this.iNVOICENOField;
            }
            set {
                this.iNVOICENOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORDERNO {
            get {
                return this.oRDERNOField;
            }
            set {
                this.oRDERNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PACKCODE {
            get {
                return this.pACKCODEField;
            }
            set {
                this.pACKCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DEPOSIT {
            get {
                return this.dEPOSITField;
            }
            set {
                this.dEPOSITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VOUCHER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_EC5_BID_PAYBACK_REQUESTBIDPAYBACKMATVOUCHER[] VOUCHER {
            get {
                return this.vOUCHERField;
            }
            set {
                this.vOUCHERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ec5:wzerp:bid:payment:info")]
    public partial class DT_EC5_BID_PAYBACK_REQUESTBIDPAYBACKMATVOUCHER {
        
        private string vOUCHERNOField;
        
        private string vOUCHERYEARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOUCHERNO {
            get {
                return this.vOUCHERNOField;
            }
            set {
                this.vOUCHERNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VOUCHERYEAR {
            get {
                return this.vOUCHERYEARField;
            }
            set {
                this.vOUCHERYEARField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_EC5_BID_PAYBACK_REQ_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591