//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace WZERP_E_BUSINESS.SI_IDEC_EMARKET_PO_CONFIRM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_IDEC_EMARKET_PO_CONFIRM_A_OUTBinding", Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class SI_IDEC_EMARKET_PO_CONFIRM_A_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_IDEC_EMARKET_PO_CONFIRM_A_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_IDEC_EMARKET_PO_CONFIRM_A_OUTService() {
            this.Url = global::WZERP_E_BUSINESS.Properties.Settings.Default.WZERP_E_BUSINESS_SI_IDEC_EMARKET_PO_CONFIRM_SI_IDEC_EMARKET_PO_CONFIRM_A_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_IDEC_EMARKET_PO_CONFIRM_A_OUTCompletedEventHandler SI_IDEC_EMARKET_PO_CONFIRM_A_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_IDEC_EMARKET_PO_CONFIRM_A_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sinopec:ecc:mm:idec_mro")] DT_IDEC_EMARKET_PO_CONFIRM MT_IDEC_EMARKET_PO_CONFIRM) {
            this.Invoke("SI_IDEC_EMARKET_PO_CONFIRM_A_OUT", new object[] {
                        MT_IDEC_EMARKET_PO_CONFIRM});
        }
        
        /// <remarks/>
        public void SI_IDEC_EMARKET_PO_CONFIRM_A_OUTAsync(DT_IDEC_EMARKET_PO_CONFIRM MT_IDEC_EMARKET_PO_CONFIRM) {
            this.SI_IDEC_EMARKET_PO_CONFIRM_A_OUTAsync(MT_IDEC_EMARKET_PO_CONFIRM, null);
        }
        
        /// <remarks/>
        public void SI_IDEC_EMARKET_PO_CONFIRM_A_OUTAsync(DT_IDEC_EMARKET_PO_CONFIRM MT_IDEC_EMARKET_PO_CONFIRM, object userState) {
            if ((this.SI_IDEC_EMARKET_PO_CONFIRM_A_OUTOperationCompleted == null)) {
                this.SI_IDEC_EMARKET_PO_CONFIRM_A_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_IDEC_EMARKET_PO_CONFIRM_A_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_IDEC_EMARKET_PO_CONFIRM_A_OUT", new object[] {
                        MT_IDEC_EMARKET_PO_CONFIRM}, this.SI_IDEC_EMARKET_PO_CONFIRM_A_OUTOperationCompleted, userState);
        }
        
        private void OnSI_IDEC_EMARKET_PO_CONFIRM_A_OUTOperationCompleted(object arg) {
            if ((this.SI_IDEC_EMARKET_PO_CONFIRM_A_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_IDEC_EMARKET_PO_CONFIRM_A_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class DT_IDEC_EMARKET_PO_CONFIRM {
        
        private DT_IDEC_EMARKET_PO_CONFIRMIT_ZMROSDZCSMIGOH[] iT_ZMROSDZCSMIGOHField;
        
        private DT_IDEC_EMARKET_PO_CONFIRMIT_ZMROSDZCSMIGOL[] iT_ZMROSDZCSMIGOLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_ZMROSDZCSMIGOH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_IDEC_EMARKET_PO_CONFIRMIT_ZMROSDZCSMIGOH[] IT_ZMROSDZCSMIGOH {
            get {
                return this.iT_ZMROSDZCSMIGOHField;
            }
            set {
                this.iT_ZMROSDZCSMIGOHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_ZMROSDZCSMIGOL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_IDEC_EMARKET_PO_CONFIRMIT_ZMROSDZCSMIGOL[] IT_ZMROSDZCSMIGOL {
            get {
                return this.iT_ZMROSDZCSMIGOLField;
            }
            set {
                this.iT_ZMROSDZCSMIGOLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class DT_IDEC_EMARKET_PO_CONFIRMIT_ZMROSDZCSMIGOH {
        
        private string mSGIDField;
        
        private string lOGSYSField;
        
        private string zIDECDDHField;
        
        private string zIDECKEYField;
        
        private string zIDECNAMEField;
        
        private string eBELNField;
        
        private string zBZField;
        
        private string rESERVE1Field;
        
        private string rESERVE2Field;
        
        private string rESERVE3Field;
        
        private string rESERVE4Field;
        
        private string rESERVE5Field;
        
        private string rESERVE6Field;
        
        private string rESERVE7Field;
        
        private string rESERVE8Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGSYS {
            get {
                return this.lOGSYSField;
            }
            set {
                this.lOGSYSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECDDH {
            get {
                return this.zIDECDDHField;
            }
            set {
                this.zIDECDDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECKEY {
            get {
                return this.zIDECKEYField;
            }
            set {
                this.zIDECKEYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECNAME {
            get {
                return this.zIDECNAMEField;
            }
            set {
                this.zIDECNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBZ {
            get {
                return this.zBZField;
            }
            set {
                this.zBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE1 {
            get {
                return this.rESERVE1Field;
            }
            set {
                this.rESERVE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE2 {
            get {
                return this.rESERVE2Field;
            }
            set {
                this.rESERVE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE3 {
            get {
                return this.rESERVE3Field;
            }
            set {
                this.rESERVE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE4 {
            get {
                return this.rESERVE4Field;
            }
            set {
                this.rESERVE4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE5 {
            get {
                return this.rESERVE5Field;
            }
            set {
                this.rESERVE5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE6 {
            get {
                return this.rESERVE6Field;
            }
            set {
                this.rESERVE6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE7 {
            get {
                return this.rESERVE7Field;
            }
            set {
                this.rESERVE7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESERVE8 {
            get {
                return this.rESERVE8Field;
            }
            set {
                this.rESERVE8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sinopec:ecc:mm:idec_mro")]
    public partial class DT_IDEC_EMARKET_PO_CONFIRMIT_ZMROSDZCSMIGOL {
        
        private string zIDECKJXYField;
        
        private string zIDECDDHField;
        
        private string zIDECDDHXMHField;
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string zDHQRField;
        
        private string eRFMGField;
        
        private string eRFMEField;
        
        private string zBZField;
        
        private string zYL1Field;
        
        private string zYL2Field;
        
        private string zYL3Field;
        
        private string zYL4Field;
        
        private string zYL5Field;
        
        private string zYL6Field;
        
        private string zYL7Field;
        
        private string zYL8Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECKJXY {
            get {
                return this.zIDECKJXYField;
            }
            set {
                this.zIDECKJXYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECDDH {
            get {
                return this.zIDECDDHField;
            }
            set {
                this.zIDECDDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIDECDDHXMH {
            get {
                return this.zIDECDDHXMHField;
            }
            set {
                this.zIDECDDHXMHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZDHQR {
            get {
                return this.zDHQRField;
            }
            set {
                this.zDHQRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERFMG {
            get {
                return this.eRFMGField;
            }
            set {
                this.eRFMGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERFME {
            get {
                return this.eRFMEField;
            }
            set {
                this.eRFMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBZ {
            get {
                return this.zBZField;
            }
            set {
                this.zBZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL1 {
            get {
                return this.zYL1Field;
            }
            set {
                this.zYL1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL2 {
            get {
                return this.zYL2Field;
            }
            set {
                this.zYL2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL3 {
            get {
                return this.zYL3Field;
            }
            set {
                this.zYL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL4 {
            get {
                return this.zYL4Field;
            }
            set {
                this.zYL4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL5 {
            get {
                return this.zYL5Field;
            }
            set {
                this.zYL5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL6 {
            get {
                return this.zYL6Field;
            }
            set {
                this.zYL6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL7 {
            get {
                return this.zYL7Field;
            }
            set {
                this.zYL7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZYL8 {
            get {
                return this.zYL8Field;
            }
            set {
                this.zYL8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SI_IDEC_EMARKET_PO_CONFIRM_A_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591